"""add country to users

Revision ID: 37fb2ac24236
Revises: a3c0624aa624
Create Date: 2026-03-07 04:14:44.073848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fb2ac24236'
down_revision = 'a3c0624aa624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
