"""Add emotion table

Revision ID: bb9779230ae7
Revises: a63ab6c8f35d
Create Date: 2026-02-23 22:17:48.508227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb9779230ae7'
down_revision = 'a63ab6c8f35d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dominant_emotion', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('emotion_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotions_dominant_emotion'), 'emotions', ['dominant_emotion'], unique=False)
    op.create_index(op.f('ix_emotions_id'), 'emotions', ['id'], unique=False)
    op.create_index(op.f('ix_emotions_timestamp'), 'emotions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_emotions_user_id'), 'emotions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotions_user_id'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_timestamp'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_id'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_dominant_emotion'), table_name='emotions')
    op.drop_table('emotions')
    # ### end Alembic commands ###
